// Shared types between CLI pipeline and Web UI.
// Stable JSON contract — bumping SCHEMA_VERSION on breaking changes.

export const SCHEMA_VERSION = 1;

export type Speaker = "user" | "teacher";

export type Severity = "critical" | "moderate" | "minor";

export type IssueCategory =
  | "grammar"
  | "vocabulary"
  | "fluency"
  | "pronunciation"
  | "discourse";

export interface ReviewMeta {
  id: string;
  schemaVersion: number;
  createdAt: string;          // ISO 8601
  sourcePath: string;         // original mp4/mp3 path (not copied)
  sourceFilename: string;
  /**
   * Short content-based title generated by the analyzer (e.g.
   * "科技在生活中的应用"). Optional; UI falls back to sourceFilename.
   */
  title?: string;
  durationSec: number;
  audioFile: string;          // relative: "audio.wav"
  modelTranscribe: string;    // e.g. "whisper-cpp/ggml-large-v3"
  modelAnalyze: string;       // e.g. "claude-sonnet-4-6"
  language: string;           // "en"
}

export interface TranscriptSegment {
  id: string;
  startSec: number;
  endSec: number;
  speaker: Speaker;
  text: string;
  issueIds: string[];         // back-reference to Issue.id
}

export interface Issue {
  id: string;
  segmentId: string;
  severity: Severity;
  category: IssueCategory;
  original: string;           // exact phrase from segment
  suggested: string;          // corrected/idiomatic version
  explanation: string;        // Chinese explanation of why
  bandImpact?: string;        // e.g. "Lexical Resource"
}

export interface ReviewSummary {
  estimatedBandLow: number;   // e.g. 5.5
  estimatedBandHigh: number;  // e.g. 6.0
  topMistakes: string[];      // categorized patterns, not single instances
  strengths: string[];
  recommendations: string[];
  fillerWordCount: number;    // count of "okay"/"yeah"/"uh" etc
  userTalkRatio: number;      // 0-1: user talk-time / total
}

export interface ReviewAnalysis {
  meta: ReviewMeta;
  transcript: TranscriptSegment[];
  issues: Issue[];
  summary: ReviewSummary;
}
